### ISSUE TITLE
[BUG] Currently slow for large contracts

### ISSUE THREAD

**Issue by willemneal** [raendev/admin#6]
Having some loading animation should be good enough.  In the future we should perhaps cache contracts to local storage so that we only need to retrieve them if the code hash changes.

**Comment by chadoh** [comment]
Was this resolved by #12? We still do not show loading animations on first load.

**Comment by willemneal** [comment]
I think this loading animations are always good for waiting.

Also we should have a message for when a contract doesn't have a custom section.

**Comment by chadoh** [comment]
> Also we should have a message for when a contract doesn't have a custom section.

created #19 for this
